app = "khmer-groq-bot-v2"
primary_region = "sin"

[build]

[env]
  NODE_ENV = "production"
  PORT = "8080"

[[services]]
  internal_port = 8080
  protocol = "tcp"

  [[services.tcp_checks]]
    interval = "15s"
    timeout  = "10s"
